name: Build OpenImageIO on Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies (vcpkg)
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg.exe install boost zlib libjpeg-turbo libpng tiff openexr opencv fmt robin-map pugixml pybind11 libjxl libheif freetype opencolorio opencv tbb ffmpeg giflib libraw openjpeg qtbase
          echo "VCPKG_ROOT=$pwd\vcpkg" >> $env:GITHUB_ENV

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" `
            -DOIIO_BUILD_TESTS=OFF `
            -DBUILD_SHARED_LIBS=ON `
            -DUSE_PYTHON=OFF `
            -DUSE_JPEGXL=ON `
            -DUSE_LIBHEIF=ON `
            -DUSE_FREETYPE=ON `
            -DUSE_OCIO=ON `
            -DUSE_OPENCV=ON `
            -DUSE_FFMPEG=ON `
            -DUSE_GIF=ON `
            -DUSE_LIBRAW=ON `
            -DUSE_OPENJPEG=ON `
            -DOpenImageIO_BUILD_MISSING_DEPS=all

      - name: Build with MSBuild
        run: |
          cd build
          cmake --build . --config Release --parallel

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenImageIO-Windows-Build
          path: |
            build/Release/*.dll
            build/Release/*.exe
